project:
  title: "DOM_Review"
  type: manuscript
  render: 
    - Manuscript.qmd
    - Analysis/Analysis.qmd
  execute-dir: project

manuscript:
  article: Manuscript.qmd
  meca-bundle: false

format: 
  html:
    theme: simplex
  docx: default

bibliography: references.bib
csl: apa.csl 

editor: visual

