project:
  type: manuscript
  execute-dir: project
  output-dir: Writing
  render:
    - domReview.qmd
    - Randomisation/Randomise_Papers.qmd
    
manuscript:
  article: domReview.qmd
  notebooks: 
    - notebook: Randomisation/Randomise_Papers.qmd
      title: Paper Randomisation
  resources:
    - Spreadsheets/Stage3_Spreadsheet.xlsx


format:
  html:
    theme: minty
  docx: default

execute:
  freeze: true



