project:
  type: manuscript
  output-dir: Outputs
  execute-dir: project

manuscript:
  article: domReview.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: simplex
  docx: default