---
title: Basic summary of included papers
output:
  html_document: default
  pdf_document: default
---

***
 
```{r setup, echo = FALSE, message = FALSE}
library("knitr")
library("tidyverse") 
library("readxl")

opts_knit$set(root.dir = "/Users/kelleherj/Documents/Research/QAEco/ODM_Review/dynamic-occupancy-model-review/")
```


```{r Read spreadsheet, echo = FALSE, message = FALSE}
regex <- c("Academic|Government|NGO|Private")

summarySheet <- readxl::read_xlsx("Data/SelectedSummaries.xlsx") %>%
  mutate(Include = case_when(Include == "Y" ~ "Included",
                             Include == "N" ~ "Not Included")) %>%
  mutate(Query = case_when(Query == "Dynamic occupancy model" ~ "DOM",
                           Query == "Occupancy dynamics model" ~ "ODM",
                           Query == "Multi-season occupancy model" ~ "MSOM",
                           Query == "Stochastic patch occupancy model" ~ "SPOM")) %>%
  mutate(Query = factor(Query, levels = c("DOM", "ODM", "MSOM", "SPOM"))) %>%
  mutate(Academic = grepl("Academic", Practitioner)) %>%
  mutate(Government = grepl("Government", Practitioner)) %>%
  mutate(Private = grepl("Private", Practitioner)) %>%
  mutate(NGO = grepl("NGO", Practitioner)) %>%
  mutate(Covariates = case_when(Covariates == "Y" ~ 1,
                                Covariates == "N" ~ 0))
```


## Qualified papers 
```{R overall qualified, echo = FALSE, message = FALSE}
summarySheet %>%
  mutate(Include = as.factor(Include)) %>%
  count(Query, Include, name = "Papers", .drop = FALSE) %>%
  
  ggplot(aes(x = Query, y = Papers, fill = Include)) +
  geom_col(position = "dodge") + 
  scale_fill_manual(values = c("dodgerblue3", "firebrick3")) +
  ggtitle("Inclusion by query") +
  theme(legend.title = element_blank())
```

## Authorship Organisation
```{r Organisation, echo = FALSE, message = FALSE}
summarySheet %>%
  filter(Include == "Included") %>%
  summarize(Total = n(),
            Academic = sum(Academic)/Total,
            Government = sum(Government)/Total, 
            NGO = sum(NGO)/Total,
            Private = sum(Private)/Total) %>%
  pivot_longer(cols = c(Academic, Government, NGO, Private), names_to = "Practitioner", values_to = "Proportion") %>%
  
  ggplot(aes(x = Practitioner, y = Proportion, fill = Practitioner)) +
  geom_col(position = "dodge") +
  ggtitle("Proportion of papers by authorship category") +
  theme(legend.title = element_blank()) +
  ylim(0,1)
```


## Covariates
```{r Covariate use, echo = FALSE, message = FALSE}
summarySheet %>%
  filter(Include == "Included") %>%
  summarize(Prop = sum(Covariates)/n()) %>%
  
  ggplot(aes(x = , y = Prop)) +
  geom_col(fill = "dodgerblue4") + 
  ggtitle("Proportion using covariates") +
  ylim(0,1)
```



```{r spreadsheet for goals}
regex <- c("Management|Methods|Invasives|Conservation|Research")

summarySheet2 <- readxl::read_xlsx("Data/SelectedSummaries.xlsx") %>%
  mutate(Include = case_when(Include == "Y" ~ "Included",
                             Include == "N" ~ "Not Included")) %>%
  mutate(Query = case_when(Query == "Dynamic occupancy model" ~ "DOM",
                           Query == "Occupancy dynamics model" ~ "ODM",
                           Query == "Multi-season occupancy model" ~ "MSOM",
                           Query == "Stochastic patch occupancy model" ~ "SPOM")) %>%
  mutate(Query = factor(Query, levels = c("DOM", "ODM", "MSOM", "SPOM"))) %>%
  mutate(Methods = grepl("Methods", Objective)) %>%
  mutate(Management = grepl("Management", Objective)) %>%
  mutate(Conservation = grepl("Conservation", Objective)) %>%
  mutate(Research = grepl("Research", Objective)) %>%
  mutate(Invasives = grepl("Invasives", Objective)) %>%
  mutate(Covariates = case_when(Covariates == "Y" ~ 1,
                                Covariates == "N" ~ 0))

summarySheet2 %>%
  filter(Include == "Included") %>%
  summarize(Total = n(),
            Methods = sum(Methods)/Total,
            Research = sum(Research)/Total, 
            Management = sum(Management)/Total,
            Conservation = sum(Conservation)/Total,
            Invasives = sum(Invasives)/Total) %>%
  pivot_longer(cols = c(Methods, Research, Management, Conservation, Invasives), 
               names_to = "Objectives", values_to = "Proportion") %>%
  
  ggplot(aes(x = Objectives, y = Proportion, fill = Objectives)) +
  geom_col(position = "dodge") +
  ggtitle("Proportion of papers by objective category") +
  theme(legend.title = element_blank()) +
  ylim(0,1)
```


